name: Install, build and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # NOTE: 20.x does not work yet for us!
        # We only support 18.x
        node-version:
          - "18.x"

    steps:
      - uses: actions/checkout@v3
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: sudo apt-get install libfuse-dev
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
